AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LeadingCommentSpace:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
